require "simple_form"

module Lms
  class Engine < ::Rails::Engine
    isolate_namespace Lms

    # Add engine's assets to loading path
    # config.before_configuration do
    #   config.assets.paths << root.join("app/assets/builds")
    # end

    # Configure paths for asset pipeline
    config.before_configuration do
      # Add the engine's assets to the load path
      config.assets.paths << root.join("app/assets/stylesheets")
      config.assets.paths << root.join("app/assets/tailwind")
      config.assets.paths << root.join("app/assets/builds")
      config.assets.paths << root.join("app/javascript")
    end

    # Add engine's built CSS to precompile list
    initializer "lms.assets" do |app|
      app.config.assets.precompile += %w[lms/admin/tailwind.css]
      app.config.assets.precompile += %w[lms/application.css]
      app.config.assets.precompile += %w[lms/admin/application.css]
    end

    # Make sure engine's importmap is loaded after main app's importmap
    initializer "lms.importmap", before: "importmap" do |app|
      app.config.importmap.paths << root.join("config/admin_importmap.rb")
      app.config.importmap.cache_sweepers << root.join("app/javascript")
    end

    initializer "lms.tailwind" do |app|
      app.config.tailwind_content_paths ||= []
      app.config.tailwind_content_paths += [
        root.join("app/views/**/*.{erb,slim}").to_s,
        root.join("app/components/**/*.rb").to_s,
        root.join("app/helpers/**/*.rb").to_s,
        root.join("app/javascript/**/*.js").to_s
      ]
    end

    # Auto-update tailwind.config.js after engine loads (development only)
    # This ensures paths are updated when switching between local/GitHub gem sources
    initializer "lms.update_tailwind_config", after: :load_config_initializers do |app|
      if Rails.env.development?
        Rails.application.config.after_initialize do
          # Update tailwind.config.js with current paths
          paths = Rails.application.config.tailwind_content_paths || []

          config_content = <<~JS
            /** @type {import('tailwindcss').Config} */
            // This file is auto-generated by `rails tailwind:update_source_paths`
            // Do not edit manually - your changes will be overwritten
            // To add paths, register them in your engine's initializer or config/initializers/tailwind.rb
            export default {
              content: #{JSON.pretty_generate(paths)},
            }
          JS

          config_path = Rails.root.join('tailwind.config.js')
          File.write(config_path, config_content)

          Rails.logger.info "✓ LMS Engine: Updated tailwind.config.js with #{paths.length} content paths"
        end
      end
    end
  end
end
